#include "ScriptManager.h"

#include <algorithm>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <regex>
#include <set>
#include <spdlog/spdlog.h>
#include <sstream>

#include "OmniPlatform/OmniPlatform.h"

#if defined(OMNI_PLATFORM_WINDOWS)
#include <windows.h>
#endif

namespace fs = std::filesystem;

namespace Manager {

namespace {
#if defined(OMNI_PLATFORM_WINDOWS)
std::string GetSteamPathFromRegistry() {
    HKEY hKey;
    if (RegOpenKeyExA(HKEY_CURRENT_USER, "Software\\Valve\\Steam", 0, KEY_READ, &hKey) == ERROR_SUCCESS) {
        char buf[MAX_PATH];
        DWORD bufSize = sizeof(buf);
        DWORD type = REG_SZ;
        if (RegQueryValueExA(hKey, "SteamPath", nullptr, &type, reinterpret_cast<LPBYTE>(buf), &bufSize) ==
            ERROR_SUCCESS) {
            RegCloseKey(hKey);
            return std::string(buf);
        }
        RegCloseKey(hKey);
    }
    return "";
}
#endif
} // namespace

std::vector<std::string> ScriptManager::GetCandidateLuaDirectories() {
    std::vector<std::string> dirs;
    std::set<std::string> seen;

    auto addDir = [&](const std::string& d) {
        if (!d.empty()) {
            std::string normalized = fs::path(d).lexically_normal().generic_string();
            if (!seen.contains(normalized)) {
                seen.insert(normalized);
                dirs.push_back(normalized);
            }
        }
    };

    // 1. Local relative config/lua
    addDir("config/lua");
    addDir("lua");

#if defined(OMNI_PLATFORM_WINDOWS)
    // 2. Windows registry Steam path
    std::string regSteam = GetSteamPathFromRegistry();
    if (!regSteam.empty()) {
        addDir(regSteam + "/config/lua");
        addDir(regSteam + "/lua");
    }

    // 3. Common Windows Steam default locations
    addDir("C:/Program Files (x86)/Steam/config/lua");
    addDir("C:/Program Files/Steam/config/lua");

    const char* userProfile = std::getenv("USERPROFILE");
    if (userProfile) {
        addDir(std::string(userProfile) + "/AppData/Roaming/OmniSteam/lua");
    }
#elif defined(OMNI_PLATFORM_MACOS)
    const char* home = std::getenv("HOME");
    if (home) {
        addDir(std::string(home) + "/Library/Application Support/Steam/config/lua");
        addDir(std::string(home) + "/Library/Application Support/OmniSteam/lua");
        addDir(std::string(home) + "/.config/omnisteam/lua");
    }
#else
    const char* home = std::getenv("HOME");
    if (home) {
        addDir(std::string(home) + "/.local/share/Steam/config/lua");
        addDir(std::string(home) + "/.steam/steam/config/lua");
        addDir(std::string(home) + "/.config/omnisteam/lua");
    }
#endif

    return dirs;
}

std::string ScriptManager::GetDefaultLuaDirectory() {
    auto candidates = GetCandidateLuaDirectories();
    for (const auto& d : candidates) {
        if (fs::exists(d)) {
            return d;
        }
    }

#if defined(OMNI_PLATFORM_WINDOWS)
    return "C:/Program Files (x86)/Steam/config/lua";
#elif defined(OMNI_PLATFORM_MACOS)
    const char* home = std::getenv("HOME");
    return home ? (std::string(home) + "/Library/Application Support/Steam/config/lua") : "/tmp/omnisteam/lua";
#else
    const char* home = std::getenv("HOME");
    return home ? (std::string(home) + "/.local/share/Steam/config/lua") : "/tmp/omnisteam/lua";
#endif
}

std::string ScriptManager::GenerateLuaScript(const UnlockGameSpec& spec) {
    std::ostringstream oss;
    oss << "-- ==============================================================================\n";
    oss << "-- OmniSteam Auto Generated Game Unlock Script\n";
    oss << "-- Game: " << spec.gameName << " (AppID: " << spec.appId << ")\n";
    oss << "-- Generated by OmniSteam Manager\n";
    oss << "-- ==============================================================================\n\n";

    // 1. Primary App ID
    if (!spec.depotKeyHex.empty()) {
        oss << "-- Unlock Main Game with Depot Decryption Key\n";
        oss << "addappid(" << spec.appId << ", 0, \"" << spec.depotKeyHex << "\")\n\n";
    } else {
        oss << "-- Unlock Main Game\n";
        oss << "addappid(" << spec.appId << ")\n\n";
    }

    // 2. Access Token if present
    if (!spec.accessToken.empty()) {
        oss << "-- Access Token\n";
        oss << "addtoken(" << spec.appId << ", \"" << spec.accessToken << "\")\n\n";
    }

    // 3. Custom Manifest ID if present
    if (!spec.customManifestId.empty()) {
        oss << "-- Manifest Pin\n";
        oss << "setManifestid(" << spec.appId << ", \"" << spec.customManifestId << "\")\n\n";
    }

    // 4. DLC App IDs
    if (!spec.dlcAppIds.empty()) {
        oss << "-- Unlock All DLCs (" << spec.dlcAppIds.size() << " items)\n";
        for (uint32_t dlcId : spec.dlcAppIds) {
            oss << "addappid(" << dlcId << ")\n";
        }
        oss << "\n";
    }

    return oss.str();
}

bool ScriptManager::SaveGameUnlock(const UnlockGameSpec& spec, const std::string& targetDir) {
    std::string dir = targetDir.empty() ? GetDefaultLuaDirectory() : targetDir;
    try {
        fs::create_directories(dir);
        std::string filename = std::to_string(spec.appId) + ".lua";
        std::string fullPath = dir + "/" + filename;

        std::string content = GenerateLuaScript(spec);
        std::ofstream out(fullPath, std::ios::trunc);
        if (!out) {
            spdlog::error("ScriptManager: Failed to write to {}", fullPath);
            return false;
        }

        out << content;
        spdlog::info("ScriptManager: Successfully saved unlock script for {} to {}", spec.appId, fullPath);
        return true;
    } catch (const std::exception& e) {
        spdlog::error("ScriptManager: Exception while saving script: {}", e.what());
        return false;
    }
}

std::vector<ScriptFileInfo> ScriptManager::ListScripts(const std::string& targetDir) {
    std::vector<ScriptFileInfo> list;
    std::set<std::string> seenPaths;

    std::vector<std::string> searchDirs;
    if (!targetDir.empty()) {
        searchDirs.push_back(targetDir);
    } else {
        searchDirs = GetCandidateLuaDirectories();
    }

    for (const auto& dir : searchDirs) {
        if (!fs::exists(dir))
            continue;

        try {
            for (const auto& entry : fs::recursive_directory_iterator(dir)) {
                if (!entry.is_regular_file())
                    continue;

                std::string filename = entry.path().filename().string();
                bool isLua = filename.ends_with(".lua");
                bool isDisabled = filename.ends_with(".lua.disabled");

                if (isLua || isDisabled) {
                    std::string canonicalPath = fs::canonical(entry.path()).generic_string();
                    if (seenPaths.contains(canonicalPath))
                        continue;
                    seenPaths.insert(canonicalPath);

                    ScriptFileInfo info;
                    info.fileName = filename;
                    info.fullPath = entry.path().generic_string();
                    info.fileSize = entry.file_size();
                    info.enabled = isLua;

                    std::regex idRegex("^(\\d+)");
                    std::smatch match;
                    if (std::regex_search(filename, match, idRegex)) {
                        info.primaryAppId = static_cast<uint32_t>(std::stoul(match[1].str()));
                    }

                    std::ifstream in(info.fullPath);
                    std::string line;
                    while (std::getline(in, line)) {
                        if (line.rfind("-- Game: ", 0) == 0) {
                            info.title = line.substr(9);
                            break;
                        }
                    }

                    list.push_back(info);
                }
            }
        } catch (...) {
        }
    }

    return list;
}

bool ScriptManager::ToggleScript(const std::string& filePath, bool enable) {
    try {
        if (!fs::exists(filePath))
            return false;

        std::string newPath;
        if (enable && filePath.ends_with(".disabled")) {
            newPath = filePath.substr(0, filePath.length() - 9); // Remove .disabled
        } else if (!enable && filePath.ends_with(".lua")) {
            newPath = filePath + ".disabled";
        } else {
            return true; // Already in requested state
        }

        fs::rename(filePath, newPath);
        spdlog::info("ScriptManager: Renamed {} -> {}", filePath, newPath);
        return true;
    } catch (const std::exception& e) {
        spdlog::error("ScriptManager: Toggle failed: {}", e.what());
        return false;
    }
}

bool ScriptManager::DeleteScript(const std::string& filePath) {
    try {
        if (fs::exists(filePath)) {
            fs::remove(filePath);
            spdlog::info("ScriptManager: Deleted script {}", filePath);
            return true;
        }
        return false;
    } catch (const std::exception& e) {
        spdlog::error("ScriptManager: Delete failed: {}", e.what());
        return false;
    }
}

} // namespace Manager
