#include "ScriptManager.h"

#include <algorithm>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <regex>
#include <set>
#include <spdlog/spdlog.h>
#include <sstream>
#include <string>
#include <vector>

#include "OmniPlatform/OmniPlatform.h"

namespace fs = std::filesystem;

namespace Manager {

std::vector<std::string> ScriptManager::GetCandidateLuaDirectories() {
    return OmniPlatform::Paths::GetCandidateLuaDirectories();
}

std::string ScriptManager::GetDefaultLuaDirectory() {
    return OmniPlatform::Paths::GetDefaultLuaDirectory();
}

std::string ScriptManager::GenerateLuaScript(const UnlockGameSpec& spec) {
    std::ostringstream oss;
    oss << "-- ==============================================================================\n";
    oss << "-- OmniSteam Auto Generated Game Unlock & Denuvo Ticket Script\n";
    oss << "-- Game: " << spec.gameName << " (AppID: " << spec.appId << ")\n";
    oss << "-- Generated by OmniSteam\n";
    oss << "-- ==============================================================================\n\n";

    // 1. Primary App ID & Main Depot Decryption Key
    std::set<uint32_t> emittedAppIds;
    emittedAppIds.insert(spec.appId);

    auto itMainKey = spec.depotKeys.find(spec.appId);
    std::string mainKey =
        !spec.depotKeyHex.empty() ? spec.depotKeyHex : (itMainKey != spec.depotKeys.end() ? itMainKey->second : "");

    if (!mainKey.empty()) {
        oss << "-- Unlock Main Game with Depot Decryption Key\n";
        oss << "addappid(" << spec.appId << ", 0, \"" << mainKey << "\")\n\n";
    } else {
        oss << "-- Unlock Main Game\n";
        oss << "addappid(" << spec.appId << ")\n\n";
    }

    // 2. Extra Depot Keys for Main Game
    std::set<uint32_t> dlcSet(spec.dlcAppIds.begin(), spec.dlcAppIds.end());
    bool hasGameDepots = false;
    for (const auto& [depotId, keyHex] : spec.depotKeys) {
        if (depotId != spec.appId && dlcSet.find(depotId) == dlcSet.end() && !keyHex.empty()) {
            if (!hasGameDepots) {
                oss << "-- Main Game Depots (Decryption Keys)\n";
                hasGameDepots = true;
            }
            oss << "addappid(" << depotId << ", 0, \"" << keyHex << "\")\n";
            emittedAppIds.insert(depotId);
        }
    }
    if (hasGameDepots) {
        oss << "\n";
    }

    // 3. DLC App IDs (with their respective depot keys if available)
    if (!spec.dlcAppIds.empty()) {
        oss << "-- Unlock All DLCs (" << spec.dlcAppIds.size() << " items)\n";
        for (uint32_t dlcId : spec.dlcAppIds) {
            auto it = spec.depotKeys.find(dlcId);
            if (it != spec.depotKeys.end() && !it->second.empty()) {
                oss << "addappid(" << dlcId << ", 0, \"" << it->second << "\")\n";
            } else {
                oss << "addappid(" << dlcId << ")\n";
            }
            emittedAppIds.insert(dlcId);
        }
        oss << "\n";
    }

    // 4. Access Token if present
    if (!spec.accessToken.empty()) {
        oss << "-- Access Token\n";
        oss << "addtoken(" << spec.appId << ", \"" << spec.accessToken << "\")\n\n";
    }

    // 5. Custom Manifest ID if present
    if (!spec.customManifestId.empty()) {
        oss << "-- Manifest Pin\n";
        oss << "setManifestid(" << spec.appId << ", \"" << spec.customManifestId << "\")\n\n";
    }

    // 6. Denuvo & App Ownership Tickets (All-In-One)
    if (!spec.appTicketHex.empty()) {
        oss << "-- Denuvo / App Ownership Ticket\n";
        oss << "setAppTicket(" << spec.appId << ", \"" << spec.appTicketHex << "\")\n\n";
    }
    if (!spec.eTicketHex.empty()) {
        oss << "-- Denuvo Encrypted Ticket (ETicket)\n";
        oss << "setETicket(" << spec.appId << ", \"" << spec.eTicketHex << "\")\n\n";
    }

    return oss.str();
}

bool ScriptManager::SaveGameUnlock(const UnlockGameSpec& spec, const std::string& targetDir) {
    std::string dir = targetDir.empty() ? GetDefaultLuaDirectory() : targetDir;
    try {
        fs::create_directories(dir);
        std::string filename = std::to_string(spec.appId) + ".lua";
        std::string fullPath = dir + "/" + filename;

        std::string content = GenerateLuaScript(spec);
        std::ofstream out(fullPath, std::ios::trunc);
        if (!out) {
            spdlog::error("ScriptManager: Failed to write to {}", fullPath);
            return false;
        }

        out << content;
        spdlog::info("ScriptManager: Successfully saved unlock script for {} to {}", spec.appId, fullPath);
        return true;
    } catch (const std::exception& e) {
        spdlog::error("ScriptManager: Exception while saving script: {}", e.what());
        return false;
    }
}

std::vector<ScriptFileInfo> ScriptManager::ListScripts(const std::string& targetDir) {
    std::vector<ScriptFileInfo> list;
    std::set<std::string> seenPaths;

    std::vector<std::string> searchDirs;
    if (!targetDir.empty()) {
        searchDirs.push_back(targetDir);
    } else {
        searchDirs = GetCandidateLuaDirectories();
    }

    for (const auto& dir : searchDirs) {
        if (!fs::exists(dir))
            continue;

        try {
            for (const auto& entry : fs::recursive_directory_iterator(dir)) {
                if (!entry.is_regular_file())
                    continue;

                std::string filename = entry.path().filename().string();
                bool isLua = filename.ends_with(".lua");
                bool isDisabled = filename.ends_with(".lua.disabled");

                if (isLua || isDisabled) {
                    std::string canonicalPath = fs::canonical(entry.path()).generic_string();
                    if (seenPaths.contains(canonicalPath))
                        continue;
                    seenPaths.insert(canonicalPath);

                    ScriptFileInfo info;
                    info.fileName = filename;
                    info.fullPath = entry.path().generic_string();
                    info.fileSize = entry.file_size();
                    info.enabled = isLua;

                    std::regex idRegex("^(\\d+)");
                    std::smatch match;
                    if (std::regex_search(filename, match, idRegex)) {
                        info.primaryAppId = static_cast<uint32_t>(std::stoul(match[1].str()));
                    }

                    std::ifstream in(info.fullPath);
                    std::string line;
                    while (std::getline(in, line)) {
                        if (line.rfind("-- Game: ", 0) == 0) {
                            info.title = line.substr(9);
                            break;
                        }
                    }

                    list.push_back(info);
                }
            }
        } catch (...) {
        }
    }

    return list;
}

bool ScriptManager::ToggleScript(const std::string& filePath, bool enable) {
    try {
        if (!fs::exists(filePath))
            return false;

        std::string newPath;
        if (enable && filePath.ends_with(".disabled")) {
            newPath = filePath.substr(0, filePath.length() - 9); // Remove .disabled
        } else if (!enable && filePath.ends_with(".lua")) {
            newPath = filePath + ".disabled";
        } else {
            return true; // Already in requested state
        }

        fs::rename(filePath, newPath);
        spdlog::info("ScriptManager: Renamed {} -> {}", filePath, newPath);
        return true;
    } catch (const std::exception& e) {
        spdlog::error("ScriptManager: Toggle failed: {}", e.what());
        return false;
    }
}

bool ScriptManager::DeleteScript(const std::string& filePath) {
    try {
        if (fs::exists(filePath)) {
            fs::remove(filePath);
            spdlog::info("ScriptManager: Deleted script {}", filePath);
            return true;
        }
        return false;
    } catch (const std::exception& e) {
        spdlog::error("ScriptManager: Delete failed: {}", e.what());
        return false;
    }
}

} // namespace Manager
