[patterns.ConfigStore_GetBinary]
module = "steamclient.so"
pattern = "55 48 89 E5 41 57 41 56 41 55 41 54 53 48 83 EC"
offset = 0

[patterns.IPCProcessMessage]
module = "steamclient.so"
pattern = "55 48 89 E5 41 57 41 56 41 55 41 54 49 89 D4"
offset = 0

[patterns.BGetCallback]
module = "steamclient.so"
pattern = "55 48 89 E5 41 57 41 56 53 48 83 EC"
offset = 0
