[patterns.ConfigStore_GetBinary]
module = "steamclient.dylib"
pattern = "55 48 89 E5 41 57 41 56 41 55 41 54"
offset = 0

[patterns.IPCProcessMessage]
module = "steamclient.dylib"
pattern = "55 48 89 E5 41 57 41 56"
offset = 0
