#pragma once

#ifndef OMNISTEAM_VERSION
#define OMNISTEAM_VERSION "1.0.0"
#define OMNISTEAM_VERSION_MAJOR 1
#define OMNISTEAM_VERSION_MINOR 0
#define OMNISTEAM_VERSION_PATCH 0
#define OMNISTEAM_GIT_COMMIT "dev"
#define OMNISTEAM_BUILD_TIMESTAMP "2026-08-20 00:00:00 UTC"
#endif
